definitions:
  responses.StandardResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  responses.UploadSuccessResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      paths:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /{directory}:
    post:
      consumes:
      - multipart/form-data
      description: Sube un archivo a S3 y lo asocia al usuario que lo subió.
      parameters:
      - description: Directorio donde se guardará el archivo
        in: path
        name: directory
        required: true
        type: string
      - description: Archivo a subir
        in: formData
        name: files
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UploadSuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.StandardResponse'
      summary: Sube un archivo a S3 y lo asocia al usuario que lo subió
      tags:
      - Files
  /files/:directory/:file:
    get:
      consumes:
      - application/json
      description: Obtiene un archivo de S3
      parameters:
      - description: Directorio donde se encuentra el archivo
        in: path
        name: directory
        required: true
        type: string
      - description: Nombre del archivo
        in: path
        name: file
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.StandardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.StandardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.StandardResponse'
      summary: Obtiene un archivo de S3
      tags:
      - Files
swagger: "2.0"
